import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { loadDecisionRecord, type VanityDecisionRecord } from "@/lib/decision-record";

export const Route = createFileRoute("/record")({
  component: DecisionRecordPage,
  head: () => ({ meta: [{ title: "Vanity Decision Record · Spa Intelligence" }, { name: "description", content: "One local record of concern, constraints, evidence, decisions and history across Vanity or Vice desks." }] }),
});

function DecisionRecordPage() {
  const [record, setRecord] = useState<VanityDecisionRecord | null>(null);
  useEffect(() => setRecord(loadDecisionRecord()), []);
  return <main className="mx-auto max-w-5xl px-5 py-12 md:px-8 md:py-16"><p className="eyebrow">Vanity or Vice · local-first</p><h1 className="mt-3 font-display text-4xl md:text-6xl">Your Decision Record</h1><p className="mt-4 max-w-2xl text-sm leading-relaxed text-(--ink-soft)">One file for what was wanted, what was known, what remained open, what was decided and what happened next. Spa retains upstream context without converting it into candidacy or provider quality.</p>{!record ? <Empty/> : <Record record={record}/>}</main>;
}
function Empty(){return <section className="mt-10 border border-(--rule) bg-(--parchment) p-6"><h2 className="font-display text-2xl">No Decision Record yet.</h2><p className="mt-2 text-sm text-(--ink-soft)">Accept a record from another Vanity desk or save a Spa setting/consult record.</p><Link to="/" className="mt-5 inline-flex text-sm text-(--oxblood) underline-offset-4 hover:underline">Open Spa Intelligence →</Link></section>}
function Record({record}:{record:VanityDecisionRecord}){return <div className="mt-10 space-y-10"><section className="grid gap-px border border-(--rule) bg-(--rule) md:grid-cols-4"><Stat label="Concern" value={record.concern||"Not named"}/><Stat label="Last source" value={record.lastSource.app}/><Stat label="Evidence" value={String(record.evidence.length)}/><Stat label="History" value={String(record.history.length)}/></section><section className="grid gap-8 md:grid-cols-2"><List title="Goals" items={record.goals}/><List title="Constraints" items={record.constraints}/></section><section><p className="eyebrow">Evidence receipts</p><div className="mt-4 space-y-3">{record.evidence.length?record.evidence.map((e)=><article key={e.id} className="border border-(--rule) bg-(--parchment) p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-display text-2xl">{e.claim}</h2><span className="font-mono text-xs text-(--ink-soft)">checked {e.checkedAt}</span></div><p className="mt-2 text-sm">{e.source}</p><p className="mt-2 font-mono text-xs text-(--ink-soft)">{e.exactObjectMatch} match · {e.confidence} confidence · {e.commercialContext} · {e.correctionState}</p>{e.uncertainty.length?<p className="mt-3 text-sm text-(--ink-soft)">Uncertainty · {e.uncertainty.join(" ")}</p>:null}</article>):<p className="text-sm text-(--ink-soft)">No receipts attached yet.</p>}</div></section><section><p className="eyebrow">Decision history</p><ol className="mt-4 divide-y divide-(--rule) border-y border-(--rule)">{[...record.history].reverse().map((h)=><li key={h.id} className="py-4"><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="text-sm font-medium">{h.label}</p><p className="font-mono text-xs text-(--ink-soft)">{h.app} · {new Date(h.at).toLocaleString()}</p></div>{h.detail?<p className="mt-1 text-sm leading-relaxed text-(--ink-soft)">{h.detail}</p>:null}</li>)}</ol></section></div>}
function Stat({label,value}:{label:string;value:string}){return <div className="bg-(--bone) p-4"><p className="font-mono text-[0.625rem] uppercase tracking-[0.16em] text-(--ink-soft)">{label}</p><p className="mt-1 text-sm">{value}</p></div>}
function List({title,items}:{title:string;items:string[]}){return <section><p className="eyebrow">{title}</p><ul className="mt-3 space-y-1 text-sm text-(--ink-soft)">{items.length?items.map((x)=><li key={x}>· {x}</li>):<li>None recorded.</li>}</ul></section>}
