/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DecodeRouteImport } from './routes/decode'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as MethodRouteImport } from './routes/method'
import { Route as PacketRouteImport } from './routes/packet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DecodeRoute = DecodeRouteImport.update({
  id: '/decode',
  path: '/decode',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const PacketRoute = PacketRouteImport.update({
  id: '/packet',
  path: '/packet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decode': typeof DecodeRoute
  '/desk': typeof DeskRoute
  '/library': typeof LibraryRoute
  '/method': typeof MethodRoute
  '/packet': typeof PacketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decode': typeof DecodeRoute
  '/desk': typeof DeskRoute
  '/library': typeof LibraryRoute
  '/method': typeof MethodRoute
  '/packet': typeof PacketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decode': typeof DecodeRoute
  '/desk': typeof DeskRoute
  '/library': typeof LibraryRoute
  '/method': typeof MethodRoute
  '/packet': typeof PacketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decode' | '/desk' | '/library' | '/method' | '/packet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decode' | '/desk' | '/library' | '/method' | '/packet'
  id:
    '__root__' | '/' | '/decode' | '/desk' | '/library' | '/method' | '/packet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecodeRoute: typeof DecodeRoute
  DeskRoute: typeof DeskRoute
  LibraryRoute: typeof LibraryRoute
  MethodRoute: typeof MethodRoute
  PacketRoute: typeof PacketRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decode': {
      id: '/decode'
      path: '/decode'
      fullPath: '/decode'
      preLoaderRoute: typeof DecodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packet': {
      id: '/packet'
      path: '/packet'
      fullPath: '/packet'
      preLoaderRoute: typeof PacketRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecodeRoute: DecodeRoute,
  DeskRoute: DeskRoute,
  LibraryRoute: LibraryRoute,
  MethodRoute: MethodRoute,
  PacketRoute: PacketRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
